apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: appversion={{ .Values.image }}/bmet-clearance-dev
  #   argocd-image-updater.argoproj.io/appversion.force-update: "true"
  #   argocd-image-updater.argoproj.io/appversion.helm.image-name: appversion.image
  #   argocd-image-updater.argoproj.io/appversion.helm.image-tag: appversion.tag
  #   argocd-image-updater.argoproj.io/appversion.pull-secret: secret:argocd/aws-ecr-creds#creds
  #   argocd-image-updater.argoproj.io/write-back-method: git:repocreds
  #   argocd-image-updater.argoproj.io/git-branch: main

spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: sohag-test
  source:
    path: app-dev
    repoURL: {{ .Values.REPOURL }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true


